--<ScriptOptions statementTerminator=";"/>

CREATE TABLE TBL_USER_ACCOUNT (
		USERID VARCHAR2(50) NOT NULL,
		USERNAME VARCHAR2(50) NOT NULL,
		PASSWORD VARCHAR2(50) NOT NULL,
		BIRTH CHAR(10) NOT NULL,
		GENDER VARCHAR2(50) NOT NULL,
		EMAIL VARCHAR2(50)
	);

CREATE UNIQUE INDEX SYS_C007377 ON TBL_USER_ACCOUNT (USERID ASC);

CREATE UNIQUE INDEX SYS_C007378 ON TBL_USER_ACCOUNT (EMAIL ASC);

ALTER TABLE TBL_USER_ACCOUNT ADD CONSTRAINT SYS_C007377 PRIMARY KEY (USERID);

